# Generated by Django 5.1.4 on 2025-08-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='chosen_choice',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
