# Generated by Django 5.1.4 on 2025-08-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0003_answer_chosen_answer_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='link',
            field=models.CharField(default='link', max_length=255),
        ),
    ]
