# Generated by Django 5.1.4 on 2025-08-03 23:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0004_quiz_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='code_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='answer',
            name='num_submission',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='answer',
            name='submitted_code',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CodeExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_code', models.TextField(blank=True)),
                ('allow_resubmission', models.BooleanField(default=False)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_exercise', to='quizApp.question')),
            ],
        ),
    ]
