# Generated by Django 5.1.4 on 2025-08-04 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0005_answer_code_rating_answer_num_submission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='code_rating',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='num_submission',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='submitted_code',
        ),
        migrations.DeleteModel(
            name='CodeExercise',
        ),
    ]
