# Generated by Django 5.1.4 on 2025-08-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0006_remove_answer_code_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='total_score',
            field=models.IntegerField(),
        ),
    ]
