# Generated by Django 5.1.4 on 2025-08-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0007_alter_leaderboardentry_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='ranking_score',
            field=models.IntegerField(default=0),
        ),
    ]
