# Generated by Django 5.1.4 on 2025-09-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0009_alter_question_option_a_alter_question_option_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=99999),
        ),
    ]
