# Generated by Django 5.1.4 on 2025-10-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0010_alter_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
