# Generated by Django 5.1.4 on 2025-10-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0011_alter_leaderboardentry_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='ranking_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='total_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
