# Generated by Django 5.1.4 on 2025-08-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='reference_code',
            field=models.TextField(blank=True),
        ),
    ]
