# Generated by Django 5.1.4 on 2025-08-05 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseApp', '0002_exercise_reference_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters, underscores, and hyphens are allowed.', regex='^[a-zA-Z0-9_-]+$')]),
        ),
    ]
