# Generated by Django 5.1.4 on 2025-08-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseApp', '0004_completedexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(blank=True),
        ),
    ]
