# Generated by Django 5.1.4 on 2025-08-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseApp', '0005_alter_exercise_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='reference_code',
            field=models.TextField(),
        ),
    ]
