# Generated by Django 5.1.4 on 2025-08-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseApp', '0006_alter_exercise_reference_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('type', models.CharField(max_length=90)),
                ('code', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'SpecialExercises',
            },
        ),
    ]
