# Generated by Django 5.1.4 on 2025-08-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseApp', '0007_specialexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialexercise',
            name='verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
