# Generated by Django 5.1.4 on 2025-08-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseApp', '0009_specialexercise_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialexercise',
            name='title',
            field=models.CharField(max_length=90, unique=True),
        ),
    ]
