# Generated by Django 5.1.4 on 2025-08-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseApp', '0010_alter_specialexercise_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialexercise',
            name='title',
            field=models.CharField(max_length=90),
        ),
    ]
