# Generated by Django 5.1.4 on 2025-08-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseApp', '0012_exerciseremarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseremarks',
            name='code',
            field=models.TextField(default="console.log('Your code')"),
        ),
    ]
