# Generated by Django 5.1.4 on 2025-09-26 06:19

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseApp', '0013_exerciseremarks_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='Images/')),
            ],
        ),
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='Videos/')),
            ],
        ),
    ]
