# Generated by Django 5.1.4 on 2025-09-27 04:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseApp', '0014_imageupload_videoupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
