# Generated by Django 5.1.4 on 2025-09-19 16:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribtion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={},
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='price',
            new_name='price_cfa',
        ),
        migrations.RenameField(
            model_name='usersubscription',
            old_name='subscribed_on',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='expires_on',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
