# Generated by Django 5.1.4 on 2025-09-19 16:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribtion', '0002_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
