# Generated by Django 5.1.4 on 2025-09-20 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribtion', '0003_alter_usersubscription_subscription_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['price_usd']},
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='is_upgrade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='previous_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgraded_from', to='subscribtion.usersubscription'),
        ),
    ]
