# Generated by Django 5.1.4 on 2025-09-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribtion', '0004_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='upgrade_price_cfa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='upgrade_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
