# Generated by Django 5.1.4 on 2025-09-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribtion', '0005_usersubscription_upgrade_price_cfa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='is_upgrade',
            field=models.BooleanField(default=True),
        ),
    ]
