# Generated by Django 5.1.4 on 2025-10-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribtion', '0006_alter_usersubscription_is_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='previous_plan_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='previous_plan_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='upgrade_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
