# Generated by Django 5.1.4 on 2025-10-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribtion', '0007_subscriptionplan_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_cfa',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
