# Generated by Django 5.1.4 on 2025-08-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchbytecub',
            old_name='link_title',
            new_name='link',
        ),
        migrations.AddField(
            model_name='searchbytecub',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
