# Generated by Django 5.1.4 on 2025-08-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_link_title_searchbytecub_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchbytecub',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='searchbytecub',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
