# Generated by Django 5.1.4 on 2025-08-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_searchbytecub_link_alter_searchbytecub_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchbytecub',
            name='link',
        ),
        migrations.AddField(
            model_name='searchbytecub',
            name='url_name',
            field=models.CharField(default=1, help_text='The full HTML link snippet, e.g., \'<a href="{% url \'link_name\' %}"><li class="class name"> Some name</li></a>\'', max_length=255),
            preserve_default=False,
        ),
    ]
