# Generated by Django 5.1.4 on 2025-08-13 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_searchbytecub_link_searchbytecub_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchbytecub',
            name='title',
        ),
    ]
